# Based on https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
name: CI
env:
  NODE_ENV: ci

on:
  push:
    branches:
      - main
      - develop
      - testing
  pull_request:
    branches:
      - main
      - develop
      - testing

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.18.1
          cache: "npm"
      - run: npm ci
      - run: npx prisma generate
      - run: NODE_ENV=$NODE_ENV npm run build --if-present
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
      - run: npm run test:unit
