name: run integration testing
on:
  pull_request:
    branches:
      - main
      - develop
      - testing

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    runs-on: ubuntu-latest
    environment: ci
    strategy:
      matrix:
        node-version: [16.x]
    services:
      db:
        image: postgres:13
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
          POSTGRES_DB: tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Integration testing
        run: |
          npx prisma db push
          npm run test:integration
        env:
          DATABASE_URL: ${{ secrets.APP_DATABASE_URL }}
